set terminal png size 1400,900
set output 'dictionary_growth.png'
set datafile separator ','
set logscale xy
set grid
set key outside
set multiplot layout 4,2 title 'Dictionary Operation Growth'
set title 'Search'
set xlabel 'Number of elements (n)'
set ylabel 'Operation count'
plot 'search.csv' using 1:2 with linespoints title 'Unsorted array', 'search.csv' using 1:3 with linespoints title 'Sorted array', 'search.csv' using 1:4 with linespoints title 'Singly linked unsorted list', 'search.csv' using 1:5 with linespoints title 'Singly linked sorted list', 'search.csv' using 1:6 with linespoints title 'Doubly linked unsorted list', 'search.csv' using 1:7 with linespoints title 'Doubly linked sorted list'
set title 'Insert'
set xlabel 'Number of elements (n)'
set ylabel 'Operation count'
plot 'insert.csv' using 1:2 with linespoints title 'Unsorted array', 'insert.csv' using 1:3 with linespoints title 'Sorted array', 'insert.csv' using 1:4 with linespoints title 'Singly linked unsorted list', 'insert.csv' using 1:5 with linespoints title 'Singly linked sorted list', 'insert.csv' using 1:6 with linespoints title 'Doubly linked unsorted list', 'insert.csv' using 1:7 with linespoints title 'Doubly linked sorted list'
set title 'Delete'
set xlabel 'Number of elements (n)'
set ylabel 'Operation count'
plot 'delete.csv' using 1:2 with linespoints title 'Unsorted array', 'delete.csv' using 1:3 with linespoints title 'Sorted array', 'delete.csv' using 1:4 with linespoints title 'Singly linked unsorted list', 'delete.csv' using 1:5 with linespoints title 'Singly linked sorted list', 'delete.csv' using 1:6 with linespoints title 'Doubly linked unsorted list', 'delete.csv' using 1:7 with linespoints title 'Doubly linked sorted list'
set title 'Maximum'
set xlabel 'Number of elements (n)'
set ylabel 'Operation count'
plot 'maximum.csv' using 1:2 with linespoints title 'Unsorted array', 'maximum.csv' using 1:3 with linespoints title 'Sorted array', 'maximum.csv' using 1:4 with linespoints title 'Singly linked unsorted list', 'maximum.csv' using 1:5 with linespoints title 'Singly linked sorted list', 'maximum.csv' using 1:6 with linespoints title 'Doubly linked unsorted list', 'maximum.csv' using 1:7 with linespoints title 'Doubly linked sorted list'
set title 'Minimum'
set xlabel 'Number of elements (n)'
set ylabel 'Operation count'
plot 'minimum.csv' using 1:2 with linespoints title 'Unsorted array', 'minimum.csv' using 1:3 with linespoints title 'Sorted array', 'minimum.csv' using 1:4 with linespoints title 'Singly linked unsorted list', 'minimum.csv' using 1:5 with linespoints title 'Singly linked sorted list', 'minimum.csv' using 1:6 with linespoints title 'Doubly linked unsorted list', 'minimum.csv' using 1:7 with linespoints title 'Doubly linked sorted list'
set title 'Predecessor'
set xlabel 'Number of elements (n)'
set ylabel 'Operation count'
plot 'predecessor.csv' using 1:2 with linespoints title 'Unsorted array', 'predecessor.csv' using 1:3 with linespoints title 'Sorted array', 'predecessor.csv' using 1:4 with linespoints title 'Singly linked unsorted list', 'predecessor.csv' using 1:5 with linespoints title 'Singly linked sorted list', 'predecessor.csv' using 1:6 with linespoints title 'Doubly linked unsorted list', 'predecessor.csv' using 1:7 with linespoints title 'Doubly linked sorted list'
set title 'Successor'
set xlabel 'Number of elements (n)'
set ylabel 'Operation count'
plot 'successor.csv' using 1:2 with linespoints title 'Unsorted array', 'successor.csv' using 1:3 with linespoints title 'Sorted array', 'successor.csv' using 1:4 with linespoints title 'Singly linked unsorted list', 'successor.csv' using 1:5 with linespoints title 'Singly linked sorted list', 'successor.csv' using 1:6 with linespoints title 'Doubly linked unsorted list', 'successor.csv' using 1:7 with linespoints title 'Doubly linked sorted list'
unset multiplot
